----------------------------------------------------------------------  Modified Files:  	XMLSchema.py -- now we get reasonable error message back when 		import or include is incorrectly defined.
  File "/usr/local/lib/python2.3/site-packages/ZSI/wstools/XMLSchema.py", line 478, in __checkAttributes
    raise SchemaError, '%s, unknown attribute' %a
ZSI.wstools.XMLSchema.SchemaError: location, unknown attribute


 ----------------------------------------------------------------------


git-svn-id: http://svn.code.sf.net/p/pywebsvcs/code/trunk@386 7150bf37-e60d-0410-b93f-83e91ef0e581