M    generate/containers.py -- failure to check for SOAP.ENC namespace in addition to XSD.LIST. -- when setting up the "ofwhat", error attempt to grab a typecode class def lookup via "Namespaces.getAlias" when this is a built-in type (SOAP.ENC)
[ 1790384 ] wsdl2py bug - schemaLocation attribute:
Using wsdl2py (from svn) on this wsdl:

http://nws.cs.ucsb.edu:8180/axis/services/Nws?wsdl

I get:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/wsdl2py", line 8, in <module>
    load_entry_point('ZSI==2.1.dev-r1412', 'console_scripts', 'wsdl2py')()
  File "/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/commands.py", line 147, in wsdl2py
   
  File "/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/commands.py", line 233, in _wsdl2py
   
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/wsdl2python.py", line 212, in writeClient
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/wsdl2python.py", line 340, in write
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/wsdl2python.py", line 361, in __str__
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/containers.py", line 271, in getvalue
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/containers.py", line 974, in _setContent
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/containers.py", line 1789, in getTypecodeList
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/containers.py", line 1781, in _setTypecodeList
  File "build/bdist.macosx-10.3-fat/egg/ZSI/generate/utility.py", line 72, in getAlias
ZSI.generate.WsdlGeneratorError: failed to find import for schema "http://schemas.xmlsoap.org/soap/encoding/"possibly missing @schemaLocation attribute.

While I go off and dig into the idiosyncrasies of wsdl specs, thought I'd throw this out to the list to see if someone can provide a clue.

thanks, Randy



git-svn-id: http://svn.code.sf.net/p/pywebsvcs/code/trunk@1413 7150bf37-e60d-0410-b93f-83e91ef0e581