M    wsdl2py/config.txt A    wsdl2py/test_InfoBil.py Fix for [ 1482042 ] schema import bug rpc/enc Axis 1.4 WSDL
wsdl2py.py -u http://javatest2.infodata.se/webservices/services/
Infobil?wsdl
Traceback (most recent call last):
File "/usr/bin/wsdl2py.py", line 5, in ?
pkg_resources.run_script('ZSI==2.0-rc2', 'wsdl2py.py')
File "/usr/lib/python2.3/site-packages/setuptools-0.6a8-py2.3.egg/
pkg_resources.py", line 407, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.3/site-packages/setuptools-0.6a8-py2.3.egg/
pkg_resources.py", line 927, in run_script
exec script_code in namespace, namespace
File "/usr/bin/wsdl2py.py", line 221, in ?
File "/usr/bin/wsdl2py.py", line 216, in main
File "build/bdist.linux-i686/egg/ZSI/generate/wsdl2python.py", line 
226, in writeTypes
File "build/bdist.linux-i686/egg/ZSI/generate/wsdl2python.py", line 396, 
in fromSchema
File "build/bdist.linux-i686/egg/ZSI/generate/wsdl2python.py", line 523, 
in fromSchemaItem
File "build/bdist.linux-i686/egg/ZSI/generate/containers.py", line 2163, 
in setUp
File "build/bdist.linux-i686/egg/ZSI/wstools/XMLSchema.py", line 600, 
in getSchemaItem
AttributeError: (u'Failure in setUp: <schema targetNamespace="http://
infobil.soap.infodata.sema.se"><complexType 
name="ArrayOf_tns3_PT31">', "XMLSchema instance has no attribute 
'getSchema'")


git-svn-id: http://svn.code.sf.net/p/pywebsvcs/code/trunk@1273 7150bf37-e60d-0410-b93f-83e91ef0e581